# Generated by Django 3.2.6 on 2021-08-14 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='trainer_images', verbose_name='Фото тренера')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст')),
                ('citizenship', django_countries.fields.CountryField(default='', max_length=2, verbose_name='Гражданство')),
                ('slug', models.SlugField(default='', help_text='ссылка на профиль тренера', max_length=130, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('year_of_foundation', models.PositiveSmallIntegerField(blank=True, verbose_name='Год основания')),
                ('league', models.CharField(max_length=50, verbose_name='Лига')),
                ('logo', models.ImageField(default='default.jpg', upload_to='team_images', verbose_name='Лого команды')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('slug', models.SlugField(default='', help_text='ссылка на профиль команды', max_length=130, unique=True, verbose_name='Ссылка')),
                ('content', tinymce.models.HTMLField(blank=True, default='', max_length=5000, verbose_name='Информация о команде')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='teams.trainer', verbose_name='тренеры')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
