# Generated by Django 3.1.7 on 2021-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('year_of_foundation', models.PositiveSmallIntegerField(blank=True, verbose_name='Год основания')),
                ('league', models.CharField(max_length=50, verbose_name='Лига')),
                ('logo', models.ImageField(default='default.jpg', upload_to='team_images', verbose_name='Лого команды')),
                ('captain', models.CharField(max_length=100, verbose_name='Капитан')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('slug', models.SlugField(default='', help_text='ссылка на профиль команды', max_length=130, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Книга',
            },
        ),
    ]
