# Generated by Django 3.1.7 on 2021-04-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
    ]
