# Generated by Django 3.1.7 on 2021-04-11 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тренер')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='trainer_images', verbose_name='Фото тренера')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Возраст')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='teams.trainer', verbose_name='тренеры'),
        ),
    ]
