# Generated by Django 3.1.7 on 2021-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210411_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='slug',
            field=models.SlugField(default='', help_text='ссылка на профиль тренера', max_length=130, unique=True, verbose_name='Ссылка'),
        ),
    ]
