# Generated by Django 3.1.7 on 2021-04-12 06:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20210411_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=5000, verbose_name='Информация о команде'),
        ),
    ]
