# Generated by Django 3.1.7 on 2021-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player_team'),
        ('teams', '0009_team_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.Player', verbose_name='Игроки'),
        ),
    ]
