# Generated by Django 3.1.7 on 2021-04-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
