# Generated by Django 3.2 on 2021-07-15 21:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_trainer_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
