# Generated by Django 3.2.6 on 2021-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchstatistic',
            name='assists',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ассисты'),
        ),
        migrations.AlterField(
            model_name='playermatchstatistic',
            name='goals',
            field=models.IntegerField(blank=True, default=0, verbose_name='Голы'),
        ),
        migrations.AlterField(
            model_name='playermatchstatistic',
            name='removes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Удаления'),
        ),
    ]
