# Generated by Django 3.2.6 on 2021-08-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20210810_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='statistic.playermatchstatistic', verbose_name='Статистика')),
            ],
            options={
                'verbose_name': 'Очко команды',
                'verbose_name_plural': 'Очки команды',
            },
        ),
    ]
