# Generated by Django 3.2.6 on 2021-08-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_matchstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchStatistic',
        ),
    ]
