# Generated by Django 3.2.6 on 2021-08-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_auto_20210813_1358'),
        ('statistic', '0004_delete_matchstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstatistic',
            name='match',
        ),
        migrations.AddField(
            model_name='playermatchstatistic',
            name='match',
            field=models.ManyToManyField(related_name='match', to='match.Match', verbose_name='Матч'),
        ),
    ]
