# Generated by Django 3.2.6 on 2021-08-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', help_text='ссылка на матч', max_length=130, unique=True, verbose_name='Ссылка')),
                ('first_team_goals', models.IntegerField(default=0, verbose_name='Голы первой команды')),
                ('second_team_goals', models.IntegerField(default=0, verbose_name='Голы второй команды')),
                ('result', models.CharField(default='0 - 0', max_length=15, verbose_name='Счет')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('first_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_matches', to='teams.team', verbose_name='первая команда')),
                ('second_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_matches', to='teams.team', verbose_name='вторая команда')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
