# Generated by Django 3.1.7 on 2021-04-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_team'),
        ('teams', '0011_remove_team_players'),
        ('match', '0002_auto_20210412_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_matches', to='teams.team', verbose_name='первая команда'),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_matches', to='teams.team', verbose_name='вторая команда'),
        ),
        migrations.CreateModel(
            name='PlayerMatchStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, verbose_name='Голы')),
                ('assists', models.IntegerField(blank=True, verbose_name='Ассисты')),
                ('removes', models.IntegerField(blank=True, verbose_name='Удаления')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='match.match', verbose_name='матч')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='players.player', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
