# Generated by Django 3.2.5 on 2021-07-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20210702_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerMatchStatistics',
        ),
    ]
