# Generated by Django 3.2.5 on 2021-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_delete_playermatchstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, verbose_name='Голы')),
            ],
        ),
    ]
