# Generated by Django 3.2.5 on 2021-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': 'Гол', 'verbose_name_plural': 'Голы'},
        ),
        migrations.AddField(
            model_name='goals',
            name='match',
            field=models.ManyToManyField(related_name='match', to='match.Match', verbose_name='матч'),
        ),
    ]
