# Generated by Django 3.2.5 on 2021-07-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20210721_1151'),
        ('match', '0007_auto_20210721_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='player',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player', to='players.player', verbose_name='Игрок'),
        ),
    ]
