# Generated by Django 3.2.5 on 2021-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_goals_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Ассисты'),
        ),
    ]
