# Generated by Django 3.2.5 on 2021-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_goals_assists'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='removes',
            field=models.IntegerField(default=0, verbose_name='Удаления'),
        ),
    ]
