# Generated by Django 3.2 on 2021-08-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_goals_removes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
