# Generated by Django 3.2.6 on 2021-08-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_matchstatistics_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstatistics',
            name='player',
        ),
    ]
