# Generated by Django 3.2.6 on 2021-08-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_remove_matchstatistics_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchStatistics',
        ),
    ]
