# Generated by Django 3.2.6 on 2021-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_delete_matchstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_ended',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(default='0 - 0', max_length=15, verbose_name='Счет'),
        ),
    ]
