# Generated by Django 3.2.6 on 2021-08-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_auto_20210813_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_team_goals',
            field=models.IntegerField(default=0, verbose_name='Голы первой команды'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team_goals',
            field=models.IntegerField(default=0, verbose_name='Голы второй команды'),
        ),
    ]
