# Generated by Django 3.1.7 on 2021-04-09 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20210410_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='player_images', verbose_name='Фото игрока')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия игрока')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('slug', models.SlugField(default='', help_text='ссылка на профиль игрока', max_length=130, unique=True, verbose_name='Ссылка')),
                ('height', models.PositiveSmallIntegerField(blank=True, verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(blank=True, verbose_name='Вес')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='teams.team', verbose_name='команда')),
            ],
        ),
    ]
