# Generated by Django 3.1.7 on 2021-04-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок'},
        ),
    ]
