# Generated by Django 3.1.7 on 2021-04-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Позиция'),
        ),
    ]
