# Generated by Django 3.1.7 on 2021-04-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=20, verbose_name='Возраст'),
        ),
    ]
