# Generated by Django 3.1.7 on 2021-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_reserve',
            field=models.BooleanField(default=False, verbose_name='Запасной'),
        ),
    ]
