# Generated by Django 3.1.7 on 2021-04-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_is_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
