# Generated by Django 3.1.7 on 2021-04-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_remove_team_players'),
        ('players', '0008_remove_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='teams.team', verbose_name='команда'),
        ),
    ]
