# Generated by Django 3.2 on 2021-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер игрока'),
        ),
    ]
