# Generated by Django 3.2.5 on 2021-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_delete_playermatchstatistics'),
        ('players', '0012_alter_player_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ManyToManyField(related_name='matches', to='match.Match', verbose_name='Матчи'),
        ),
    ]
