# Generated by Django 3.2.5 on 2021-07-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_goals'),
        ('players', '0014_player_match_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='match_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_goals', to='match.goals', verbose_name='Голы'),
        ),
    ]
