# Generated by Django 3.2.5 on 2021-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20210721_1112'),
        ('players', '0015_alter_player_match_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match_goals',
        ),
        migrations.AddField(
            model_name='player',
            name='match_goals',
            field=models.ManyToManyField(blank=True, related_name='player_goals', to='match.Goals', verbose_name='Голы'),
        ),
    ]
