# Generated by Django 3.2.6 on 2021-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20210721_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Ассисты'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Голы'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
    ]
