# Generated by Django 3.2.6 on 2021-08-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20210810_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
    ]
